version: '3.8'
services:
  web-server:
    container_name: cge-surveys-php-apache
    build:
      context: ./docker/web-server
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html/
      - ./docker/web-server/vhosts:/etc/apache2/sites-enabled
    ports:
      - "80:80"
      - "443:443"
  db:
    container_name: cge-surveys-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"